platform: linux
inputs:
  - name: target
outputs:
  - name: kubeconfig
params:
  GCLOUD_PROJECT_ID:
  GCLOUD_SERVICE_ACCOUNT:
  GKE_CLUSTER_NAME:
  GKE_CLUSTER_REGION:
run:
  dir: target
  path: ci/scripts/generate-kubeconfig.sh
