resources:
  - name: customer-keeper-api
    type: git
    source:
      uri: https://github.com/zackvalentine/customer-keeper-api.git
      branch: add-local-ci

  - name: customer-keeper-api-dcind-openjdk11
    type: docker-image
    source:
      repository: zackvalentine/customer-keeper-api
      email: ((docker_email))
      username: ((docker_user))
      password: ((docker_password))

  - name: final-docker-image
    type: docker-image
    source:
      repository: gcr.io/gleaming-aegis-288600/customer-keeper-api

  - name: gcloud-util
    type: docker-image
    source:
      repository: gcr.io/gleaming-aegis-288600/gcloud-util
      tag: 242.0.1

jobs:
  - name: verify
    build_logs_to_retain: 50
    plan:
      - in_parallel:
          - get: target
            resource: customer-keeper-api
            trigger: true
          - get: customer-keeper-api-dcind-openjdk11
            passed: [build-verify-image]
            params:
              save: true
      - task: build
        privileged: true
        image: customer-keeper-api-dcind-openjdk11
        file: target/ci/tasks/build.yml
        on_success:
          put: final-docker-image
          params:
            load_file: build-output/image/tgz
            load_repository: customer-keeper-api
            load_tag: SNAPSHOT
            tag: build-output/tag

  - name: deploy-dev
    build_logs_to_retain: 50
    plan:
      - in_parallel:
          - get: target
            resource: customer-keeper-api
            trigger: true
          - get: gcloud-util
          - get: customer-keeper-api-dcind-openjdk11
            passed: [build-verify-image]f
      - task: generate-kubeconfig
        image: gcloud-util
        file: target/ci/tasks/generate-kubeconfig.yml
        params:
          GCLOUD_PROJECT_ID: ((gcloud_project_id.dev))
          GCLOUD_SERVICE_ACCOUNT: ((gcloud_ci_service_account.dev))
          GKE_CLUSTER_NAME: apps-v1-us-central1
          GKE_CLUSTER_REGION: us-central1
      - task: deploy
        image: gcr.gleaming-aegis-288600/customer-keeper-api
        file: target/ci/tasks/deploy.yml
        params:
          ENVIRONMENT: dev
          GCLOUD_PROJECT_ID: ((gcloud_project_id.dev))
          GCLOUD_SERVICE_ACCOUNT: ((gcloud_app_service_account.dev))

  - name: build-verify-image
    build_logs_to_retain: 50
    plan:
      - get: add-local-ci
        resource: customer-keeper-api
        trigger: true
      - try:
          task: build-container
          file: add-local-ci/ci/tasks/build-container.yml
          on_success:
            put: customer-keeper-api-dcind-openjdk11
            params:
              build: add-local-ci/ci/dcind-openjdk11
              tag: docker-env/ref
              tag_as_latest: true